@startuml

class Data {
}
class Statistic {
}
class Sensor {
}
class Training {
}
class Recommended_Exercise {
}
class Unregistered_User {
}
class uTrack {
}
class User {
}
class Bicycle {
}
class Exercise {
}

uTrack "1" --> "*" Data : "Has data"
uTrack "1" --> "*" User : "Has"
Data "*" --> "*" Statistic : "Create"
User "1" --> "*" Statistic : "Visualise"
Unregistered_User "1" --> "1" User : "Transform to"
User "1" --> "1" Bicycle : "Has"
User "1" --> "1..*" Training : "Do"
Training "1" *-- "1..*" Exercise : "Contain"
Training "1" o-- "0,1" Recommended_Exercise : "Has"
Training "1" --> "*" Sensor : "Usa"
Sensor "1" --> "*" Data : "Provide"

@enduml